In [ ]:
import numpy as np

In [ ]:
# 一次元配列の作り方
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
# 配列の指定
a[2] = 4
a

array([1, 2, 4])

In [ ]:
# 一次元配列を二次元配列にする
b = np.array([1, 2, 3, 4, 5, 6])
b = b.reshape(2, 3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 指定の変数を変更できる
b[1, 2] = 7
b

array([[1, 2, 3],
       [4, 5, 7]])

In [ ]:
# 列数もまとめて変更できる
b[:, 2] = 8
b 

array([[1, 2, 8],
       [4, 5, 8]])